#!/usr/bin/env python

from distutils.core import setup
from quixote.qx_distutils import qx_build_py

setup(name= 'qon',
    version= '0.1-snapshot',
    author='Jim Carroll',
    author_email='jim@maplesong.com',
    url='http://www.maplesong.com',
    cmdclass= {'build_py': qx_build_py},
    package_dir= {'qon': 'lib/qon'},
    packages= ['qon',
        'qon.ui',
        'qon.ui.blocks',
        'qon.ui.blog',
        'qon.ui.group',
        'qon.ui.wiki',
        ],
    data_files= [
        ('/www/bin', [
            'etc/www/bin/opendb',
            'etc/www/bin/runzeo',
            'etc/www/bin/site',
            'etc/www/bin/start-lucene.py',
            'etc/www/bin/start-scgi.py',
            'etc/www/bin/start-zeo.py',
            'etc/www/bin/zeoctl',
            'etc/www/bin/msgfmt.py',
            'etc/www/bin/pygettext.py',
            'lib/lucene-server/start-lucene.sh',
            'lib/lucene-server/stop-lucene.sh',
            ]),
        ('/www/bin/lucene', [
            'lib/lucene-server/RangeFilter.class',    
            'lib/lucene-server/ChainedFilter.class',    
            'lib/lucene-server/Server.class',
            'lib/lucene-server/LuceneHandler.class',
            'lib/lucene-server/LuceneHandler$1HelperThread.class',
            'lib/lucene-server/LuceneHandler$2HelperThread.class',            
            'lib/lucene-server/xmlrpc-1.2-b1.jar',
            'lib/lucene-server/lucene-1.4-rc3.jar',                                    
            ]),
        ('/www/conf', ['etc/www/conf/site.conf']),
        ('/www/etc', ['etc/www/etc/zeo.conf']),
        ('/www/etc', ['etc/www/etc/zeo-auth.db.sample']),
        ('/www/sites/qon/bin', [
            'bin/create_db.py',
            'bin/cron.py',
            'bin/cron-hourly.py',
            'bin/search_reindex_all.py',            
            ]),

        ('/www/sites/qon/docroot', [
            'docroot/index.html',
            #'docroot/favicon.ico',
            'docroot/c1.jpg',
            'docroot/robots.txt',
            ]),

        ('/www/sites/qon/docroot/images', [
            'docroot/images/arrowBlank.gif',
            'docroot/images/arrowDown.gif',
            'docroot/images/arrowDownAlternative.gif',
            'docroot/images/arrowUp.gif',
            'docroot/images/bullet.gif',
            'docroot/images/discussionitem_icon.gif',
            'docroot/images/file_icon.gif',
            'docroot/images/folder_icon.gif',            
            'docroot/images/group.gif',
            'docroot/images/linkOpaque.gif',
            'docroot/images/linkTransparent.gif',
            'docroot/images/link_icon.gif',
            'docroot/images/lock_icon.gif',
            'docroot/images/logo.jpg',
            'docroot/images/mail_icon.gif',
            'docroot/images/personal_news.gif',
            'docroot/images/phone_icon.gif',
            'docroot/images/poll_icon.gif',            
            'docroot/images/required.gif',
            'docroot/images/search_icon.gif',
            'docroot/images/select_all_icon.gif',
            'docroot/images/select_none_icon.gif',            
            'docroot/images/textsize_large.gif',
            'docroot/images/textsize_normal.gif',
            'docroot/images/textsize_small.gif',
            'docroot/images/topic_icon.gif',
            'docroot/images/user.gif',
            'docroot/images/widgetbullet.gif',            
            'docroot/images/xml.gif',            
            ]),
            
        ('/www/sites/qon/docroot/js', [
            'docroot/js/plone_javascript_variables.js',
            'docroot/js/plone_javascripts.js',
            'docroot/js/plone_menu.js',
            'docroot/js/MochiKit/MochiKit.js',
            'docroot/js/qon_tagging.js',
            'docroot/js/s_code_remote.js',            
            ]),

        ('/www/sites/qon/docroot/scss', [
            'docroot/scss/plone.css',
            'docroot/scss/ploneColumns.css',
            'docroot/scss/ploneCustom.css',
            'docroot/scss/ploneCustom_internal_colors.css',            
            'docroot/scss/ploneIEFixes.css',
            'docroot/scss/ploneNS4.css',
            'docroot/scss/plonePresentation.css',
            'docroot/scss/plonePrint.css',
            'docroot/scss/ploneTextLarge.css',
            'docroot/scss/ploneTextSmall.css',
            'docroot/scss/rstPrint.css',
            ]),

        ('/www/locale/en_US.ISO8859-1/LC_MESSAGES', [
            'etc/www/locale/en_US.ISO8859-1/LC_MESSAGES/qon.mo',
            ]),
        ],
    )
